// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    var Form, Results, Testimonials;
    Results = (function() {

      function Results() {}

      return Results;

    })();
    Testimonials = (function() {

      function Testimonials() {}

      return Testimonials;

    })();
    Form = (function() {

      Form.prototype.fields = {
        "name": "Jméno",
        "email": "E-mail",
        "phone": "Telefon",
        "company": "Firma",
        "www": "Web",
        "notes": "Zpráva"
      };

      function Form() {
        this.focusout = __bind(this.focusout, this);

        this.focusin = __bind(this.focusin, this);

        this.form_clear = __bind(this.form_clear, this);

        this.submit = __bind(this.submit, this);

        var name, text, type, _ref;
        _ref = this.fields;
        for (name in _ref) {
          text = _ref[name];
          type = name === "notes" ? "textarea" : "input";
          $("" + type + "[name=" + name + "]").focusin(this.focusin);
          $("" + type + "[name=" + name + "]").focusout(this.focusout);
          $("" + type + "[name=" + name + "]").val(text);
        }
        $("form").submit(this.submit);
      }

      Form.prototype.submit = function(event) {
        var _this = this;
        $.post("index.php", $("form").serialize(), function() {
          _this.form_clear();
          return alert("Děkujeme. Formulář byl úspěšně odeslán.");
        });
        return false;
      };

      Form.prototype.form_clear = function() {
        var name, text, type, _ref;
        _ref = this.fields;
        for (name in _ref) {
          text = _ref[name];
          type = name === "notes" ? "textarea" : "input";
          $("" + type + "[name=" + name + "]").val(text);
        }
        return $("form select")[0].selectedIndex = 0;
      };

      Form.prototype.focusin = function(event) {
        var name, target, text;
        target = $(event.target);
        name = target.attr("name");
        text = this.fields[name];
        if (target.val() === text) {
          return target.val("");
        }
      };

      Form.prototype.focusout = function(event) {
        var name, target, text;
        target = $(event.target);
        name = target.attr("name");
        text = this.fields[name];
        if (target.val() === "") {
          return target.val(text);
        }
      };

      return Form;

    })();
    return new Form();
  });

}).call(this);
